Move balance to proxy with callbacks
Xfers/StraitsX-tokens pull request #6
Opened 2020-01-23 11:06 UTC by junhaoyap

2020-01-23 13:30 UTC, jjcnn reviewed
I have left one comment on the change itself, but I also have a comment on the overall design after this change.

It seems to me that the division of responsibilities between the proxy and the token contract is now roughly such that the proxy handles the actual handling of tokens, whereas the token contract performs the permission checks, i.e., that the users involved have the appropriate permissions to perform the handling in question.

Normally this division would be handled the other way around, i.e., the user would interact with the "guard" contract which checks permissions, and if the permission check fails passes the transaction through to the token handling logic itself.

This suggests that what you really need is the following:
- An immutable token contract, only doing the handling of tokens
- A guard contract which checks user permissions, and passes transaction requests through to the token contract.
- A proxy guard which passes requests through to the guard contract.

Each time the guard contract needs to be updated, a new guard contract is deployed, and the proxy is updated to point to the new guard.

2020-01-23 13:30 UTC, jjcnn commented on contracts/xsgd_contract.scilla
>  field minters : Map ByStr20 Uint128 = Emp ByStr20 Uint128
My understanding of this change is that `balances` and `total_supply` is moved to the proxy contract to ensure that data migration is not an issue when updating the token contract.

That raises the question as to why it is not necessary to migrate the other parts of the state? Why is it not necessary to migrate `minters`, `blacklisted` and `allowed`, for instance?

The logical end point for that line of reasoning is of course that you end up with just one contract which then cannot be updated. So I guess the question that needs to be answered is this: Which parts of the logic/state of this application do you want to be able to change, and which parts should be set in stone?

As far as I can tell every possible answer to that question comes with its own set of maintenance problems, so it's a question that needs to be carefully considered. However, not considering it does not mean that the issue goes away - it just means you might inadvertently settle on an answer you aren't happy with.

2020-01-25 09:33 UTC, AmritKumar requested changes

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
> +transition proxyMint(to: ByStr20, value : Uint128)
This looks good to me.

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
> +transition mintCallBack(to: ByStr20, new_to_bal: Uint128, new_supply : Uint128)
This is good too.

2020-01-25 09:33 UTC, AmritKumar commented on contracts/xsgd_contract.scilla
> +          msg = {_tag : "mintCallBack"; _recipient : _sender; _amount : Uint128 0; to : to; new_to_bal : new_to_bal; new_supply : new_supply};
Replace `Uint128 0` with `zero`.

2020-01-25 09:33 UTC, AmritKumar commented on contracts/xsgd_contract.scilla
> +transition transferFrom (from : ByStr20, to : ByStr20, value : Uint128, initiator : ByStr20, to_bal : Uint128, from_bal : Uint128)
Looks good to me.

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
>  transition proxyTransferFrom (from : ByStr20, to : ByStr20, value : Uint128)
LGTM.

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
> +transition transferFromCallBack(from : ByStr20, to : ByStr20, new_from_bal : Uint128, new_to_bal : Uint128)
LGTM

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
> +    get_addr_bal <- balances[_sender];
@evesnow91 @junhaoyap Shouldn't this be `balances[address]`?

2020-01-25 09:33 UTC, AmritKumar commented on contracts/proxy.scilla
> +    get_addr_bal <- balances[_sender];
```suggestion
    get_addr_bal <- balances[address];
```

2020-01-25 09:35 UTC, AmritKumar commented on contracts/proxy.scilla
> +    get_addr_bal <- balances[_sender];
I have fixed it.

2020-01-25 10:18 UTC, merged